#!/bin/bash
# spotify.sh

convertsecs() {
    ((h=${1}/3600))
    ((m=(${1}%3600)/60))
    ((s=${1}%60))
    printf "%02d:%02d\n" $m $s
    #printf "%02d:%02d:%02d\n" $h $m $s
}

ACCESS_TOKEN=$(curl -s -i -H "Accept: application/json" http://localhost:8989/refresh_token)

ACCESS_TOKEN=${ACCESS_TOKEN##*:}
ACCESS_TOKEN=${ACCESS_TOKEN#\"}
ACCESS_TOKEN=${ACCESS_TOKEN%\"*}

if [[ $1 = "next" ]]; then
    printf "\t\033[1;32mskipping track...\033[0m\n"
    curl -X POST "https://api.spotify.com/v1/me/player/next" -H "Authorization: Bearer $ACCESS_TOKEN"
elif [[ $1 = "prev" ]]; then
    printf "\t\033[1;32mseeking track...\033[0m\n"
    curl -X POST "https://api.spotify.com/v1/me/player/previous" -H "Authorization: Bearer $ACCESS_TOKEN"
elif [[ $1 = "pause" ]]; then
    printf "\t\033[1;32mpausing track...\033[0m\n"
    curl -X PUT "https://api.spotify.com/v1/me/player/pause" -H "Authorization: Bearer $ACCESS_TOKEN"
elif [[ $1 = "play" ]]; then
    printf "\t\033[1;32mplaying track...\033[0m\n"
    curl -X PUT "https://api.spotify.com/v1/me/player/play" -H "Authorization: Bearer $ACCESS_TOKEN"
fi
    curl -s -H "Accept: application/json" http://localhost:8989/refresh_playback?access_token=$ACCESS_TOKEN > ~/spotifydata.json

ISPLAYING=$(cat ~/spotifydata.json | jq '.is_playing')
if [ "$ISPLAYING" = "true" ]; then
    PLAYSTATUS='►'
else
    PLAYSTATUS='┃┃'
fi

PROGRESS=$(cat ~/spotifydata.json | jq '.progress_ms')
if [[ $PROGRESS != "" ]]; then
    let "PROGRESS = $PROGRESS / 1000"
    TIMESTAMP=$(convertsecs $PROGRESS)

    TOTALTIME=$(cat ~/spotifydata.json | jq '.item.duration_ms')
    let "TOTALTIME = $TOTALTIME / 1000"
    TOTALTIMESTAMP=$(convertsecs $TOTALTIME)

    NAME=$(cat ~/spotifydata.json | jq '.item.name' -r )

    ARTIST=$(cat ~/spotifydata.json | jq '.item.artists[0].name' -r)

    ALBUM=$(cat ~/spotifydata.json | jq '.item.album.name' -r)

    printf "\t\033[1;32m$PLAYSTATUS [$TIMESTAMP/$TOTALTIMESTAMP] $ARTIST - $NAME ($ALBUM)\033[0m\n"
else
    printf "\t\033[1;32mSpotify is not running at the moment.\033[0m\n"
fi
